CLASS ZAI_DMObp_travel_u DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZAI_DMOi_travel_u .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZAI_DMObp_travel_u IMPLEMENTATION.
ENDCLASS.
