CLASS ZDMObp_bookingsupplement_d DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZDMOr_travel_d.
protected section.
private section.
ENDCLASS.



CLASS ZDMOBP_BOOKINGSUPPLEMENT_D IMPLEMENTATION.
ENDCLASS.
