CLASS ZDMObp_bookingsupplement_m DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZDMOi_travel_m.
protected section.
private section.
ENDCLASS.



CLASS ZDMOBP_BOOKINGSUPPLEMENT_M IMPLEMENTATION.
ENDCLASS.
