"! @testing ZAI_DMOCL_I_TRAVEL_TUM
"! @testing ZAI_DMOCL_C_TRAVEL_TUM
"! @testing ZAI_DMOCL_FLIGHT_LEGACY
"! @testing FUGR:ZAI_DMOFLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM ZAI_DMOtc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
