"! @testing ZDMOCL_I_TRAVEL_TUM
"! @testing ZDMOCL_C_TRAVEL_TUM
"! @testing ZDMOCL_FLIGHT_LEGACY
"! @testing FUGR:ZDMOFLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM ZDMOtc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
