CLASS ZDMObp_i_carrierslocksingle_s DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZDMOi_carrierslocksingleton_s.
protected section.
private section.
ENDCLASS.



CLASS ZDMOBP_I_CARRIERSLOCKSINGLE_S IMPLEMENTATION.
ENDCLASS.
